trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseNode@1
    inputs:
      version: '20.x'
    displayName: 'Use Node.js 20'

  - script: npm ci
    displayName: 'Install dependencies'

  - script: npm run lint
    displayName: 'Run ESLint'

  - script: npm run build
    displayName: 'Build React application'

  - script: |
      echo "Checking dist folder..."
      ls -la dist
    displayName: 'Verify dist folder'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/dist'
      artifact: 'react-dist'
      publishLocation: 'pipeline'
    displayName: 'Publish dist artifact'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'sc-cicd-react-azure'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "Deploying React application to Azure Storage..."

        az storage blob upload-batch \
          --account-name stcicdreactkasturi \
          --destination '$web' \
          --source "$(System.DefaultWorkingDirectory)/dist" \
          --overwrite true \
          --auth-mode login \
          --only-show-errors

        echo "Deployment completed successfully."
    displayName: 'Deploy React app to Azure Static Website'